-- Kelasin cloud schema (NO Supabase Auth, local login only)
-- Jalankan di Supabase SQL Editor project: rbooqhamwcqnnjongcrz
-- Catatan: mode ini mengizinkan akses anon untuk CRUD data aplikasi.

create extension if not exists "pgcrypto";

create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    nama text not null,
    email text not null unique,
    username text not null unique,
    password_hash text not null default '',
    profile_pic_url text not null default '',
    bio text not null default '',
    role text not null default 'MAHASISWA',
    created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.mata_kuliah (
    id bigint generated by default as identity primary key,
    nama text not null,
    kode text not null,
    dosen text not null,
    sks integer not null default 0,
    hari text not null,
    jam_mulai text not null,
    jam_selesai text not null,
    ruangan text not null,
    email_dosen text not null default '',
    no_hp_dosen text not null default '',
    warna text not null default '#6750A4',
    user_id uuid not null references public.users(id) on delete cascade
);

create table if not exists public.tugas (
    id bigint generated by default as identity primary key,
    mata_kuliah_id bigint not null references public.mata_kuliah(id) on delete cascade,
    judul text not null,
    deskripsi text not null default '',
    deadline bigint not null,
    prioritas text not null default 'SEDANG',
    status text not null default 'BELUM',
    pertemuan_ke integer not null default 1,
    file_uri text not null default '',
    link_url text not null default '',
    reminder_enabled boolean not null default true,
    user_id uuid not null references public.users(id) on delete cascade,
    created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.catatan (
    id bigint generated by default as identity primary key,
    mata_kuliah_id bigint references public.mata_kuliah(id) on delete set null,
    label_kustom text not null default '',
    judul text not null,
    isi text not null,
    tag text not null default '',
    file_uri text not null default '',
    user_id uuid not null references public.users(id) on delete cascade,
    updated_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.chat_messages (
    id bigint generated by default as identity primary key,
    room_id bigint not null references public.catatan(id) on delete cascade,
    sender_user_id uuid not null references public.users(id) on delete cascade,
    sender_name text not null,
    text text not null,
    created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.materi (
    id bigint generated by default as identity primary key,
    mata_kuliah_id bigint not null references public.mata_kuliah(id) on delete cascade,
    judul text not null,
    deskripsi text not null default '',
    tipe text not null default 'LINK',
    url text not null default '',
    file_uri text not null default '',
    is_bookmarked boolean not null default false,
    user_id uuid not null references public.users(id) on delete cascade,
    created_at bigint not null default (extract(epoch from now()) * 1000)::bigint
);

create table if not exists public.mahasiswa (
    id bigint generated by default as identity primary key,
    nama text not null,
    owner_id uuid references public.users(id) on delete cascade
);

do $$
begin
    if exists (
        select 1
        from pg_constraint
        where conname = 'mahasiswa_nama_key'
          and conrelid = 'public.mahasiswa'::regclass
    ) then
        alter table public.mahasiswa drop constraint mahasiswa_nama_key;
    end if;
end $$;

create table if not exists public.absensi (
    id bigint generated by default as identity primary key,
    mata_kuliah_id bigint not null references public.mata_kuliah(id) on delete cascade,
    mahasiswa_id bigint not null references public.mahasiswa(id) on delete cascade,
    tanggal bigint not null,
    status text not null default 'BELUM_DIPILIH',
    pertemuan_ke integer not null,
    keterangan text not null default '',
    user_id uuid not null references public.users(id) on delete cascade
);

create index if not exists idx_mata_kuliah_user_id on public.mata_kuliah(user_id);
create index if not exists idx_tugas_user_id on public.tugas(user_id);
create index if not exists idx_tugas_mk_id on public.tugas(mata_kuliah_id);
create index if not exists idx_tugas_deadline on public.tugas(deadline);
create index if not exists idx_catatan_user_id on public.catatan(user_id);
create index if not exists idx_chat_messages_room_id on public.chat_messages(room_id);
create index if not exists idx_chat_messages_created_at on public.chat_messages(created_at);
create index if not exists idx_materi_user_id on public.materi(user_id);
create index if not exists idx_absensi_user_id on public.absensi(user_id);
create index if not exists idx_absensi_mk_pertemuan on public.absensi(mata_kuliah_id, pertemuan_ke);
create index if not exists idx_mahasiswa_owner_id on public.mahasiswa(owner_id);
create unique index if not exists uq_mahasiswa_owner_nama on public.mahasiswa(owner_id, nama);

alter table public.users enable row level security;
alter table public.mata_kuliah enable row level security;
alter table public.tugas enable row level security;
alter table public.catatan enable row level security;
alter table public.chat_messages enable row level security;
alter table public.materi enable row level security;
alter table public.mahasiswa enable row level security;
alter table public.absensi enable row level security;

drop policy if exists "users_self_read" on public.users;
drop policy if exists "users_self_insert" on public.users;
drop policy if exists "users_self_update" on public.users;
drop policy if exists "users_self_delete" on public.users;
drop policy if exists "users_anon_all" on public.users;

drop policy if exists "mata_kuliah_owner_all" on public.mata_kuliah;
drop policy if exists "mata_kuliah_anon_all" on public.mata_kuliah;
drop policy if exists "tugas_owner_all" on public.tugas;
drop policy if exists "tugas_anon_all" on public.tugas;
drop policy if exists "catatan_owner_all" on public.catatan;
drop policy if exists "catatan_anon_all" on public.catatan;
drop policy if exists "chat_messages_owner_all" on public.chat_messages;
drop policy if exists "chat_messages_anon_all" on public.chat_messages;
drop policy if exists "materi_owner_all" on public.materi;
drop policy if exists "materi_anon_all" on public.materi;
drop policy if exists "absensi_owner_all" on public.absensi;
drop policy if exists "absensi_anon_all" on public.absensi;
drop policy if exists "mahasiswa_owner_select" on public.mahasiswa;
drop policy if exists "mahasiswa_owner_insert" on public.mahasiswa;
drop policy if exists "mahasiswa_owner_update" on public.mahasiswa;
drop policy if exists "mahasiswa_owner_delete" on public.mahasiswa;
drop policy if exists "mahasiswa_anon_all" on public.mahasiswa;

create policy "users_anon_all" on public.users
for all to anon, authenticated
using (true)
with check (true);

create policy "mata_kuliah_anon_all" on public.mata_kuliah
for all to anon, authenticated
using (true)
with check (true);

create policy "tugas_anon_all" on public.tugas
for all to anon, authenticated
using (true)
with check (true);

create policy "catatan_anon_all" on public.catatan
for all to anon, authenticated
using (true)
with check (true);

create policy "chat_messages_anon_all" on public.chat_messages
for all to anon, authenticated
using (true)
with check (true);

create policy "materi_anon_all" on public.materi
for all to anon, authenticated
using (true)
with check (true);

create policy "absensi_anon_all" on public.absensi
for all to anon, authenticated
using (true)
with check (true);

create policy "mahasiswa_anon_all" on public.mahasiswa
for all to anon, authenticated
using (true)
with check (true);

-- Storage bootstrap for backups bucket.
insert into storage.buckets (id, name, public)
values ('backups', 'backups', false)
on conflict (id) do nothing;

drop policy if exists "backup_objects_owner_all" on storage.objects;
drop policy if exists "backup_objects_anon_all" on storage.objects;
create policy "backup_objects_anon_all" on storage.objects
for all to anon, authenticated
using (bucket_id = 'backups')
with check (bucket_id = 'backups');
